apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: contract-app
  annotations:
    run.googleapis.com/ingress: internal-and-cloud-load-balancing
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      volumes:
      - name: liquibase-storage
        csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: liquibase-log-gcp-data-management-e0e9
            mountOptions: "implicit-dirs"
      containers:
      # Frontend container (main)
      - name: contract-ui
        image: europe-west4-docker.pkg.dev/gcp-data-management-e0e9/data-management/contract-app/contract-ui:latest
        ports:
        - name: http1
          containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_API_URL
          value: "http://localhost:8080"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: liquibase-storage
          mountPath: /mnt/liquibase
          readOnly: false
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 0
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
      
      # Backend sidecar container
      - name: contract-backend
        image: europe-west4-docker.pkg.dev/gcp-data-management-e0e9/data-management/contract-app/contract-application:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: LIQUIBASE_LOG_PATH
          value: "/mnt/liquibase"
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
        volumeMounts:
        - name: liquibase-storage
          mountPath: /mnt/liquibase
          readOnly: false
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
      
      serviceAccountName: svc-cr-data-contract@gcp-data-management-e0e9.iam.gserviceaccount.com