apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: contract-app
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      volumes:
      - name: liquibase-storage
        csi:
          driver: gcsfuse.run.googleapis.com
          volumeAttributes:
            bucketName: ${LIQUIBASE_LOG_BUCKET}
            mountOptions: "implicit-dirs"
      containers:
      # Frontend container (main) - ONLY this one has exposed port
      - name: contract-ui
        image: ${ARTIFACT_REGISTRY}/contract-ui:latest
        ports:
        - name: http1
          containerPort: 80
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: liquibase-storage
          mountPath: ${LIQUIBASE_CHANGE_PATH}
          readOnly: false
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 30
          failureThreshold: 3

      # Backend sidecar container - NO exposed port
      - name: contract-backend
        image: ${ARTIFACT_REGISTRY}/contract-application:latest
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_CLOUD_GCP_DATASTORE_PROJECT_ID
          value: "${SPRING_CLOUD_GCP_DATASTORE_PROJECT_ID}"
        - name: SPRING_CLOUD_GCP_DATASTORE_DATABASE_ID
          value: "${SPRING_CLOUD_GCP_DATASTORE_DATABASE_ID}"
        - name: LIQUIBASE_CHANGE_PATH
          value: "${LIQUIBASE_CHANGE_PATH}"
        - name: LIQUIBASE_CHANGE_DATASET
          value: "${LIQUIBASE_CHANGE_DATASET}"
        resources:
          limits:
            cpu: "1000m"
            memory: "512Mi"
        volumeMounts:
        - name: liquibase-storage
          mountPath: ${LIQUIBASE_CHANGE_PATH}
          readOnly: false
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 45
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
      
      serviceAccountName: svc-cr-data-contract@${PROJECT_ID}.iam.gserviceaccount.com